sudo: false
language: c
 
addons:
  apt:
    packages:
    - pandoc
 
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

branches:
  only:
  - /^master$|^classic$|^\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
  email:
    on_success: never
    on_failure: always